'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Search, Plus, Download, Copy, Pencil, Eye, Trash2, ChevronLeft, ChevronRight } from 'lucide-react';
import toast from 'react-hot-toast';
import { formatBDT, formatDate } from '@/lib/utils';
import type { Profile } from '@/types/quotation';

export default function QuotationHistory({role}:{role:Profile['role']}){
 const [rows,setRows]=useState<any[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(20);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [createdBy,setCreatedBy]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [profiles,setProfiles]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);const qs=new URLSearchParams({page:String(page),pageSize:String(pageSize)});if(search)qs.set('search',search);if(status)qs.set('status',status);if(createdBy)qs.set('createdBy',createdBy);if(from)qs.set('from',from);if(to)qs.set('to',to);const r=await fetch(`/api/quotations?${qs}`);const j=await r.json();if(r.ok){setRows(j.data||[]);setTotal(j.total||0);}else toast.error(j.error||'Unable to load quotations');setLoading(false);}
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[page,pageSize,search,status,createdBy,from,to]);
 useEffect(()=>{if(role==='ADMIN')fetch('/api/profiles').then(r=>r.json()).then(j=>{if(Array.isArray(j.data))setProfiles(j.data);});},[role]);
 async function duplicate(id:string){const r=await fetch(`/api/quotations/${id}/duplicate`,{method:'POST'});const j=await r.json();if(!r.ok){toast.error(j.error||'Unable to duplicate');return;}toast.success('Quotation duplicated with a new number.');window.location.href=`/quotations/${j.data.id}`;}
 async function remove(id:string){if(!confirm('Delete this quotation permanently?'))return;const r=await fetch(`/api/quotations/${id}`,{method:'DELETE'});const j=await r.json();if(!r.ok){toast.error(j.error||'Unable to delete');return;}toast.success('Quotation deleted.');load();}
 return <div><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 mb-5"><div><h1 className="text-2xl font-bold">Quotation History</h1><p className="text-sm text-slate-500">Search and manage saved BDSHOP Solar & IPS quotations.</p></div><div className="flex gap-2">{role==='ADMIN'&&<a href="/api/export" className="btn btn-secondary"><Download size={15}/> Export CSV</a>}<Link href="/new" className="btn btn-primary"><Plus size={15}/> New Quotation</Link></div></div>
 <div className="card p-4 mb-4"><div className="grid md:grid-cols-2 lg:grid-cols-5 gap-3"><div className="lg:col-span-2 relative"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input className="field pl-9" placeholder="Search quotation, customer, company, phone, prepared by" value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}}/></div><select className="field" value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}}><option value="">All statuses</option>{['Draft','Generated','Sent','Approved','Rejected','Cancelled'].map(x=><option key={x}>{x}</option>)}</select>{role==='ADMIN'&&<select className="field" value={createdBy} onChange={e=>{setPage(1);setCreatedBy(e.target.value)}}><option value="">All creators</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email}</option>)}</select>}<input className="field" type="date" value={from} onChange={e=>{setPage(1);setFrom(e.target.value)}}/><input className="field" type="date" value={to} onChange={e=>{setPage(1);setTo(e.target.value)}}/></div></div>
 <div className="card overflow-hidden"><div className="table-scroll"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="text-left p-3">Quotation</th><th className="text-left p-3">Customer</th><th className="text-left p-3">Date</th><th className="text-left p-3">Amount</th><th className="text-left p-3">Created By</th><th className="text-left p-3">Status</th><th className="text-right p-3">Actions</th></tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.id}><td className="p-3 font-semibold text-[#15458f]"><Link href={`/quotations/${r.id}`}>{r.quotation_number}</Link></td><td className="p-3"><div className="font-semibold">{r.customer_name}</div><div className="text-xs text-slate-500">{r.customer_company||'—'}</div></td><td className="p-3">{formatDate(r.quotation_date)}</td><td className="p-3">{formatBDT(Number(r.grand_total))}</td><td className="p-3">{r.profiles?.full_name||r.profiles?.email||'—'}</td><td className="p-3"><span className="px-2 py-1 rounded-full bg-slate-100 text-xs">{r.status}</span></td><td className="p-3"><div className="flex justify-end gap-1"><Link className="btn btn-ghost p-2" title="View" href={`/quotations/${r.id}`}><Eye size={15}/></Link><Link className="btn btn-ghost p-2" title="Edit" href={`/quotations/${r.id}/edit`}><Pencil size={15}/></Link><button className="btn btn-ghost p-2" title="Duplicate" onClick={()=>duplicate(r.id)}><Copy size={15}/></button>{role==='ADMIN'&&<button className="btn btn-danger p-2" title="Delete" onClick={()=>remove(r.id)}><Trash2 size={15}/></button>}</div></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-500">No quotations found.</td></tr>}{loading&&<tr><td colSpan={7} className="p-10 text-center text-slate-500">Loading...</td></tr>}</tbody></table></div><div className="p-3 border-t flex flex-col sm:flex-row gap-3 justify-between items-center text-sm"><div className="text-slate-500">{total?`${(page-1)*pageSize+1}-${Math.min(page*pageSize,total)} of ${total}`:'0 results'}</div><div className="flex items-center gap-2"><select className="field w-24 py-2" value={pageSize} onChange={e=>{setPage(1);setPageSize(Number(e.target.value))}}><option>20</option><option>50</option><option>100</option></select><button className="btn btn-secondary p-2" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></button><span>Page {page} / {Math.max(1,Math.ceil(total/pageSize))}</span><button className="btn btn-secondary p-2" disabled={page>=Math.ceil(total/pageSize)} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></button></div></div></div></div>;
}
