'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Plus, Trash2, Save, Send, ArrowUp, ArrowDown } from 'lucide-react';
import toast from 'react-hot-toast';
import { CATEGORIES, type Quotation, type QuotationItem, type QuotationSettings, type QuotationStatus } from '@/types/quotation';
import { calculateItemTotal, calculateTotals } from '@/lib/quotation/calculations';
import { formatBDT } from '@/lib/utils';
import QuotationPreview from './QuotationPreview';
import ExportButtons from './ExportButtons';
import { useRouter } from 'next/navigation';

const emptyItem=():QuotationItem=>({category:'Inverter',item_name:'',description:'',quantity:1,unit:'pcs',unit_price:0,total_price:0,sort_order:0});
const today=()=>new Date().toISOString().slice(0,10);

type FormState={quotation_number:string;customer_name:string;customer_company:string;customer_phone:string;customer_email:string;customer_address:string;customer_reference:string;quotation_date:string;validity_days:number;discount:number;tax:number;terms_and_conditions:string;status:QuotationStatus;created_by:string;creator:any;created_at:string;updated_at:string};

export default function QuotationEditor({id}:{id?:string}){
 const router=useRouter(); const previewRef=useRef<HTMLDivElement>(null);
 const [settings,setSettings]=useState<QuotationSettings|null>(null); const [loading,setLoading]=useState(!!id); const [saving,setSaving]=useState(''); const [quotationId,setQuotationId]=useState(id||'');
 const [form,setForm]=useState<FormState>({quotation_number:'DRAFT',customer_name:'',customer_company:'',customer_phone:'',customer_email:'',customer_address:'',customer_reference:'',quotation_date:today(),validity_days:10,discount:0,tax:0,terms_and_conditions:'',status:'Draft',created_by:'',creator:null,created_at:'',updated_at:''});
 const [items,setItems]=useState<QuotationItem[]>([emptyItem()]);
 useEffect(()=>{(async()=>{const s=await fetch('/api/settings');const sj=await s.json();if(s.ok)setSettings(sj.data);if(!id){if(sj.data)setForm(f=>({...f,terms_and_conditions:sj.data.default_terms}));return;}const r=await fetch(`/api/quotations/${id}`);const j=await r.json();if(!r.ok){toast.error(j.error||'Unable to load quotation');router.replace('/quotations');return;}const q=j.data as Quotation;setQuotationId(q.id);setForm({quotation_number:q.quotation_number,customer_name:q.customer_name,customer_company:q.customer_company||'',customer_phone:q.customer_phone||'',customer_email:q.customer_email||'',customer_address:q.customer_address||'',customer_reference:q.customer_reference||'',quotation_date:q.quotation_date,validity_days:q.validity_days,discount:Number(q.discount),tax:Number(q.tax),terms_and_conditions:q.terms_and_conditions,status:q.status,created_by:q.created_by,creator:q.creator,created_at:q.created_at,updated_at:q.updated_at});setItems(q.items.map((x:any)=>({...x,quantity:Number(x.quantity),unit_price:Number(x.unit_price),total_price:Number(x.total_price)})));setLoading(false);})();},[id,router]);
 const totals=useMemo(()=>calculateTotals(items,Number(form.discount)||0,Number(form.tax)||0),[items,form.discount,form.tax]);
 const previewQuotation:Quotation={id:quotationId||'preview',quotation_number:form.quotation_number,customer_name:form.customer_name||'Customer Name',customer_company:form.customer_company||null,customer_phone:form.customer_phone||null,customer_email:form.customer_email||null,customer_address:form.customer_address||null,customer_reference:form.customer_reference||null,quotation_date:form.quotation_date,validity_days:Number(form.validity_days)||10,subtotal:totals.subtotal,discount:totals.discount,tax:totals.tax,grand_total:totals.grandTotal,amount_in_words:totals.amountInWords,terms_and_conditions:form.terms_and_conditions,created_by:form.created_by,created_at:form.created_at,updated_at:form.updated_at,status:form.status,items,creator:form.creator};
 function setField<K extends keyof FormState>(key:K,value:FormState[K]){setForm(f=>({...f,[key]:value}));}
 function updateItem(index:number,patch:Partial<QuotationItem>){setItems(list=>list.map((item,i)=>i===index?{...item,...patch,total_price:calculateItemTotal(patch.quantity??item.quantity,patch.unit_price??item.unit_price)}:item));}
 function addItem(){setItems(list=>[...list,{...emptyItem(),sort_order:list.length}]);}
 function removeItem(i:number){if(items.length===1){toast.error('At least one item is required.');return;}setItems(list=>list.filter((_,idx)=>idx!==i).map((x,idx)=>({...x,sort_order:idx})));}
 function moveItem(i:number,dir:number){const j=i+dir;if(j<0||j>=items.length)return;const copy=[...items];[copy[i],copy[j]]=[copy[j],copy[i]];setItems(copy.map((x,idx)=>({...x,sort_order:idx})));}
 async function save(status:QuotationStatus){if(!form.customer_name.trim()){toast.error('Customer name is required.');return;}if(items.some(x=>!x.item_name.trim())){toast.error('Every item needs a product/item name.');return;}if(items.some(x=>x.quantity<=0||x.unit_price<0)){toast.error('Check quantity and unit price values.');return;}setSaving(status);const payload={customer_name:form.customer_name,customer_company:form.customer_company,customer_phone:form.customer_phone,customer_email:form.customer_email,customer_address:form.customer_address,customer_reference:form.customer_reference,quotation_date:form.quotation_date,validity_days:Number(form.validity_days)||10,discount:Number(form.discount)||0,tax:Number(form.tax)||0,terms_and_conditions:form.terms_and_conditions,items:items.map((x,i)=>({category:x.category,item_name:x.item_name,description:x.description,quantity:Number(x.quantity),unit:x.unit,unit_price:Number(x.unit_price),sort_order:i})),status};try{const r=await fetch(quotationId?`/api/quotations/${quotationId}`:'/api/quotations',{method:quotationId?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Save failed');const q=j.data as any;toast.success(status==='Generated'?'Quotation generated successfully.':'Quotation saved successfully.');setQuotationId(q.id);if(!quotationId||status==='Generated')router.push(`/quotations/${q.id}`);else router.refresh();}catch(e:any){toast.error(e.message||'Unable to save quotation.');}finally{setSaving('');}}
 if(loading||!settings)return <div className="py-20 text-center text-slate-500">Loading quotation...</div>;
 return <div><div className="flex flex-col xl:flex-row xl:items-center xl:justify-between gap-3 mb-5 no-print"><div><h1 className="text-2xl font-bold">{id?'Edit Quotation':'New Quotation'}</h1><p className="text-sm text-slate-500">{form.quotation_number} · backend recalculates all financial values before saving.</p></div><div className="flex flex-wrap gap-2"><button className="btn btn-secondary" onClick={()=>save('Draft')} disabled={!!saving}><Save size={15}/>{saving==='Draft'?'Saving...':id?'Save Changes':'Save Draft'}</button><button className="btn btn-primary" onClick={()=>save('Generated')} disabled={!!saving}><Send size={15}/>{saving==='Generated'?'Generating...':'Generate Quotation'}</button></div></div>
 <div className="grid xl:grid-cols-[minmax(520px,1fr)_minmax(650px,790px)] gap-6 items-start">
 <div className="space-y-5 no-print">
  <section className="card p-5"><h2 className="font-bold mb-4">Customer Information</h2><div className="grid md:grid-cols-2 gap-4"><div><label className="label">Customer Name *</label><input className="field" value={form.customer_name ?? ''} onChange={e=>setField('customer_name',e.target.value)}/></div><div><label className="label">Company / Organization</label><input className="field" value={form.customer_company} onChange={e=>setField('customer_company',e.target.value)}/></div><div><label className="label">Phone Number</label><input className="field" value={form.customer_phone} onChange={e=>setField('customer_phone',e.target.value)}/></div><div><label className="label">Email</label><input className="field" type="email" value={form.customer_email} onChange={e=>setField('customer_email',e.target.value)}/></div><div className="md:col-span-2"><label className="label">Address</label><textarea className="field min-h-20" value={form.customer_address} onChange={e=>setField('customer_address',e.target.value)}/></div><div><label className="label">Reference / Project Name</label><input className="field" value={form.customer_reference} onChange={e=>setField('customer_reference',e.target.value)}/></div><div><label className="label">Quotation Date</label><input className="field" type="date" value={form.quotation_date} onChange={e=>setField('quotation_date',e.target.value)}/></div><div><label className="label">Validity (days)</label><input className="field" type="number" min="1" value={form.validity_days} onChange={e=>setField('validity_days',Number(e.target.value))}/></div></div></section>
  <section className="card p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-bold">Quotation Items</h2><p className="text-xs text-slate-500">Unlimited rows · line totals are automatic.</p></div><button className="btn btn-secondary" onClick={addItem}><Plus size={15}/> Add Item</button></div><div className="space-y-3">{items.map((item,i)=><div key={`${i}-${item.id||'new'}`} className="border rounded-xl p-3 bg-slate-50/60"><div className="grid md:grid-cols-[130px_1fr_80px_90px_130px_auto] gap-2 items-end"><div><label className="label">Category</label><select className="field" value={item.category} onChange={e=>updateItem(i,{category:e.target.value})}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div><div><label className="label">Product / Item Name *</label><input className="field" value={item.item_name} onChange={e=>updateItem(i,{item_name:e.target.value})} placeholder={item.category==='Others'?'Custom item name':'Product name'}/></div><div><label className="label">Qty</label><input className="field" type="number" min="0.001" step="0.001" value={item.quantity} onChange={e=>updateItem(i,{quantity:Number(e.target.value)})}/></div><div><label className="label">Unit</label><input className="field" value={item.unit ?? ''} onChange={e => updateItem(i, { unit: e.target.value })}/></div><div><label className="label">Unit Price (৳)</label><input className="field" type="number" min="0" step="0.01" value={item.unit_price} onChange={e=>updateItem(i,{unit_price:Number(e.target.value)})}/></div><button className="btn btn-danger" onClick={()=>removeItem(i)} title="Delete item"><Trash2 size={16}/></button></div><div className="grid md:grid-cols-[1fr_auto] gap-2 mt-2"><div><label className="label">Description</label><input className="field" value={item.description ?? ''} onChange={e => updateItem(i, { description: e.target.value })}/></div><div className="flex items-end gap-1"><button className="btn btn-ghost" onClick={()=>moveItem(i,-1)} disabled={i===0}><ArrowUp size={15}/></button><button className="btn btn-ghost" onClick={()=>moveItem(i,1)} disabled={i===items.length-1}><ArrowDown size={15}/></button><div className="min-w-32"><div className="label">Line Total</div><div className="font-bold py-2">{formatBDT(item.total_price)}</div></div></div></div></div>)}</div></section>
  <section className="card p-5"><h2 className="font-bold mb-4">Totals & Terms</h2><div className="grid md:grid-cols-3 gap-4 mb-4"><div><label className="label">Subtotal</label><div className="field bg-slate-50 font-bold">{formatBDT(totals.subtotal)}</div></div><div><label className="label">Discount</label><input className="field" type="number" min="0" step="0.01" value={form.discount} onChange={e=>setField('discount',Number(e.target.value))}/></div><div><label className="label">Tax / VAT</label><input className="field" type="number" min="0" step="0.01" value={form.tax} onChange={e=>setField('tax',Number(e.target.value))}/></div></div><div className="rounded-lg bg-[#eef4fb] p-4 flex justify-between items-center mb-4"><span className="font-bold text-[#15458f]">Grand Total</span><span className="text-xl font-black text-[#15458f]">{formatBDT(totals.grandTotal)}</span></div><div className="mb-3"><label className="label">Amount in Words</label><div className="field bg-slate-50">{totals.amountInWords}</div></div><div><label className="label">Terms & Conditions / Notes *</label><textarea className="field min-h-48" value={form.terms_and_conditions} onChange={e=>setField('terms_and_conditions',e.target.value)}/></div></section>
 </div>
 <div className="sticky top-4"><div className="flex items-center justify-between mb-3 no-print"><div><div className="font-bold">Live Preview</div><div className="text-xs text-slate-500">Official BDSHOP A4 letterhead background.</div></div>{quotationId&&<ExportButtons quotation={previewQuotation} settings={settings} previewRef={previewRef}/>}</div><div className="bg-slate-200 p-4 rounded-xl overflow-auto"><QuotationPreview ref={previewRef} quotation={previewQuotation} settings={settings}/></div></div>
 </div></div>;
}
